### ISSUE TITLE
Чет в профиль не заходит

### ISSUE THREAD

**Issue by Murchik0v** [digitaldrugstech/prdxsotech-bugtracker#102]
### Опишите баг

Не заходит в профиль

### Шаги для воспроизведения поведения

1.Зайти на https://prdxso.tech/u/murchikov
2.Бинго профиль не работает

### Ожидаемое поведение

?

### Если возможно, прикрепите скриншоты или видео

![изображение](https://github.com/user-attachments/assets/0e0d2b9c-217e-4fd1-a5ae-3aaee927fa58)

**Comment by thehaffk** [comment]
![image](https://github.com/user-attachments/assets/b59adee8-5d78-4923-93ee-1c38c4e04a2d)


По ошибке можно догадаться что ошибка клиентская и от нас не зависит никак, мурчиков ДЕВ же
https://stackoverflow.com/questions/54232528/error-creating-webgl-context-three-js-chrome
