### ISSUE TITLE
На креативе недоступно /tp

### ISSUE THREAD

**Issue by Murchik0v** [digitaldrugstech/prdxsotech-bugtracker#106]
### Опишите баг

Не работает /tp на креативе !

### Шаги для воспроизведения поведения

1. Зайдите на теч креатив
2. Пропишите /tp 
3. оно не работает!!!!!!!!!!

### Ожидаемое поведение

телепортация

### Если возможно, прикрепите скриншоты или видео

![image](https://github.com/user-attachments/assets/99173140-265c-4fe0-a692-20ef6f036063)
![image](https://github.com/user-attachments/assets/a5a8e0dc-d373-4446-87ae-32aca4767ebb)

**Comment by thehaffk** [comment]
там хуево настроен LP
@pixiemays можешь импортировать конфиг из rp proxy в crp proxy, но не забудь CFG_ вариаблы перенести, можешь попросить кого-то либо рид доступ тебе к манифестам дать, либо попросить кого-то за теб яих настроить в ддтех чате

**Comment by pixiemays** [comment]
Сегодня порешаю

**Comment by megazvezda** [comment]
@pixiemays

**Comment by pixiemays** [comment]
в процессе

**Comment by pixiemays** [comment]
![image](https://github.com/user-attachments/assets/c2218112-1dc8-429f-b78e-400698aedf55)
