### ISSUE TITLE
Не льзя купить Fusion на сайте.

### ISSUE THREAD

**Issue by savas12-sys** [digitaldrugstech/prdxsotech-bugtracker#108]
### Опишите баг

Не льзя купить Fusion на сайте.

### Шаги для воспроизведения поведения

1.Заходите на сайт prdxso.tech
2.Переходите в профиль.
3.Нажимаете купить подписку.

### Ожидаемое поведение

Действия покупки.

**Comment by Murchik0v** [comment]
Удаляй с позором нахуй , если не умеешь читать прошлые issue то не пиши их

**Comment by thehaffk** [comment]
https://github.com/digitaldrugstech/prdxsotech-bugtracker/issues/71
