### ISSUE TITLE
Опечатка на сайте

### ISSUE THREAD

**Issue by NeytroNchik** [digitaldrugstech/prdxsotech-bugtracker#109]
![изображение](https://github.com/user-attachments/assets/8c83f566-a207-4b56-b6e7-510769f76578)

**Comment by NeytroNchik** [comment]
@pixiemays

**Comment by pixiemays** [comment]
((

**Comment by pixiemays** [comment]
а в чем опечатка?
![image](https://github.com/user-attachments/assets/829376e2-1bf0-4782-b737-ee334374502c)

**Comment by Murchik0v** [comment]
> а в чем опечатка? @NeytroNchik ![image](https://private-user-images.githubusercontent.com/89461487/398072284-829376e2-1bf0-4782-b737-ee334374502c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MzY1MzUsIm5iZiI6MTczNDkzNjIzNSwicGF0aCI6Ii84OTQ2MTQ4Ny8zOTgwNzIyODQtODI5Mzc2ZTItMWJmMC00NzgyLWI3MzctZWUzMzQzNzQ1MDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA2NDM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZGVlZWQ1MDM4ZmI5ZjYzZWM0YTU3NzgzNTUzMmI4ZDg3MWExNjEyMjgzMzY4OWVmYzYwZmMwNDU5ZGY1ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8f-ZIF9n24cRIe-k6QqZ01rxu9CwQxWkTn4-aj-Kplg)

видимо в голове человека который открыл issue

**Comment by NeytroNchik** [comment]
@pixiemays извините, хаффк у меня на демке прочитал, сказал, что неправильно написано 😔 Всё правильно на самом деле, простите🙏🙏🙏

**Comment by pixiemays** [comment]
@NeytroNchik оки, бывает

**Comment by thehaffk** [comment]
забайчен
