### ISSUE TITLE
Тикеты не работают 

### ISSUE THREAD

**Issue by Murchik0v** [digitaldrugstech/prdxsotech-bugtracker#110]
### Опишите проблему

Тикеты приняли ислам

### Шаги для воспроизведения поведения

.

### Ожидаемое поведение

открыть тикет и он открылся и закрыть и он закрылся

### Если возможно, прикрепите скриншоты или видео

![image](https://github.com/user-attachments/assets/7bb9366c-205e-46a6-8536-189b3fa123c3)
![image](https://github.com/user-attachments/assets/6e714c2f-d58e-4ac8-9635-f22eab9530e7)

**Comment by thehaffk** [comment]
как сказал один долбаеб

> Удаляй с позором нахуй , если не умеешь читать прошлые issue то не пиши их

https://github.com/digitaldrugstech/prdxsotech-bugtracker/issues/48
