### ISSUE TITLE
Бот Объявления молчит, если ему написал не игрок

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdxsotech-bugtracker#112]
Портит UX не-игрокам, надо писать в ответ хоть что-то

**Comment by Murchik0v** [comment]
Так тоже самое было если написал игрок

**Comment by Komo4ekoI** [comment]
![image](https://github.com/user-attachments/assets/ed0d5b07-7b04-4874-a86a-3b80aa7d0038)
