### ISSUE TITLE
можно ломать порталы линкованные 

### ISSUE THREAD

**Issue by Murchik0v** [digitaldrugstech/prdxsotech-bugtracker#116]
### Опишите баг

можно ломать порталы линкованные  при помощи командой

### Шаги для воспроизведения поведения

![image](https://github.com/user-attachments/assets/8b088d0a-4e16-494e-afb7-c7d59cc5dfc6)
показывает порталы которые рядом

### Ожидаемое поведение

не ломается

### Если возможно, прикрепите скриншоты или видео

![image](https://github.com/user-attachments/assets/c83a0043-a64f-4997-ba62-39d6703680c4)

**Comment by thehaffk** [comment]
нельзя (вроде)

**Comment by Murchik0v** [comment]
> нельзя (вроде)

Ну я этот иссуе создавала когда было можно

**Comment by thehaffk** [comment]
> Ну я этот иссуе создавала когда было можно

НЕ ПИШИ БРЕД В ИШЬЮ

Я ПИШУ НЕ ТЕБЕ
