### ISSUE TITLE
Пинги рендерятся во всех сообщения

### ISSUE THREAD

**Issue by megazvezda** [digitaldrugstech/prdxsotech-bugtracker#15]
### Опишите баг

В ачивках рендерятся пинги

### Шаги для воспроизведения поведения

1) Выполнить достижение
2) Получить смешной ник, звук и надпись в акшенбар

### Ожидаемое поведение

В ачивах не должны рендериться пинги

### Если возможно, прикрепите скриншоты или видео

![{E48FFDA4-0276-4F58-8DA4-5A058C919F9D}](https://github.com/user-attachments/assets/952e37ee-47d9-4c55-8993-ba789a274fba)

**Comment by thehaffk** [comment]
![image](https://github.com/user-attachments/assets/3ac5450a-52b5-4644-8344-9c1a39fd9b53)

**Comment by thehaffk** [comment]
https://github.com/digitaldrugstech/MurChat/commit/9c8137b702d90a4812d92593c75892edb4bef297
![image](https://github.com/user-attachments/assets/4e1eaad0-2077-4929-bb4f-f2583bccbbed)
