### ISSUE TITLE
Проходка на дев сервере должна выдаваться автоматически 

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdxsotech-bugtracker#19]
Нужно определиться кто и как будет ее выдавать: пепега, юзерс сервис или авторизация. Полностью автоматически или по заявкам

![IMG_20240830_200826_186.jpg](https://github.com/user-attachments/assets/aa007e44-a5cc-4983-902c-460f22b73d12)

<sub><a href="https://huly.app/guest/ddtech-66d6316d-f625710ef3-f7dbcb?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmYyZmQ5MmMyNDM5YjlmMjQ1OTlmNmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVidnJ0a2stZGR0ZWNoLTY2ZDYzMTZkLWY2MjU3MTBlZjMtZjdkYmNhIn0.3CH_ICzyW1_YiHIMQ65dZ0-fN7LbI832jtY9FNCEQ3Y">Huly&reg;: <b>PRDX-46</b></a></sub>

**Comment by shiksyt** [comment]
по заявкам кабуда норм будет

**Comment by Komo4ekoI** [comment]
О боже. мама-мама, я схожу с ума

**Comment by vrtkk** [comment]
мне кажется чтобы попасть на тех. сервер человеку нужно просто кликнуть на одну кнопку, и уже после по "заявке" принимают решение, принять/умереть :trollface:

**Comment by thehaffk** [comment]
![image](https://github.com/user-attachments/assets/fc9d5e13-f4c9-4675-b636-4ad9f2c30b73)
![image](https://github.com/user-attachments/assets/029a6478-8988-47b4-b347-93b64c4e0567)
