### ISSUE TITLE
На креативе нельзя взять плот

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdxsotech-bugtracker#21]
### Опишите баг

На креативе нельзя взять плот

### Шаги для воспроизведения поведения

1. /p claim, /p auto -> Not allowed

### Ожидаемое поведение

Allowed

### Если возможно, прикрепите скриншоты или видео

![image](https://github.com/user-attachments/assets/665b7506-c098-4852-b49c-b80f4ef15a2e)

### Любая дополнительная информация

*No response*

<sub><a href="https://huly.app/guest/ddtech-66d6316d-f625710ef3-f7dbcb?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmYyZmQ5ZWMyNDM5YjlmMjQ1OWEwNTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVidnJ0a2stZGR0ZWNoLTY2ZDYzMTZkLWY2MjU3MTBlZjMtZjdkYmNhIn0.CHQNtX5brmvnZKMcUID91DKVX3uMqyaM-AA_f3p-0os">Huly&reg;: <b>PRDX-48</b></a></sub>

**Comment by thehaffk** [comment]
Перенесли плоты с crp.plo.su

**Comment by thehaffk** [comment]
Когда берешь плоты могут взяться рандомные build;0;3 и типо того

Причина: при переносе неправильно распарсили несуществующие uuid (которые начинаются не с 0000-000000) и они стали ничейными

Фикс: перепарсили бд, теперь они оформлены на haffk

**Comment by thehaffk** [comment]
Пока фиксили проблему с занятием занятых плотов отобрали пермишен, надо бы вернуть
plots.plot.100

**Comment by Komo4ekoI** [comment]
тотальный анлаки 🧌

**Comment by vrtkk** [comment]
проблема решена, поставили лимит в 40 плотов
