### ISSUE TITLE
Диски не работают

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdxsotech-bugtracker#24]
### Опишите баг

/disc burn -> Sign in to confirm you are not a robot

### Шаги для воспроизведения поведения

1. Зайдите на /tech сервер
2. Возмите в руки пластинку
3. /disc burn	

### Ожидаемое поведение

Должно записываться

### Любая дополнительная информация

![image](https://github.com/user-attachments/assets/dc55536d-1de9-4f85-822f-c7055dd01ffc)

**Comment by thehaffk** [comment]
Комочек обновил, но там вроде не запускается плагин теперь

**Comment by Komo4ekoI** [comment]
![image](https://github.com/user-attachments/assets/e371a9ad-9ba5-47fc-84c9-48f8a04e6e09)
