### ISSUE TITLE
Мурчат неправильно работает с непереведенными компонентами

### ISSUE THREAD

**Issue by Komo4ekoI** [digitaldrugstech/prdxsotech-bugtracker#29]
### Опишите баг

Многие строки не переведены

### Шаги для воспроизведения поведения

1. Зайти на сервер
2. Открыть меню чата: /chat

### Ожидаемое поведение

Нормальный перевод

### Если возможно, прикрепите скриншоты или видео

![image](https://github.com/user-attachments/assets/8136576c-1685-4220-9528-55d1c420d00c)

**Comment by thehaffk** [comment]
Кроме того что ru_ru не настроен, мурчат не фоллбекает с русского на английский, а хотя должен

misconfiguration -> bug

**Comment by vrtkk** [comment]
ру транслейт я залил, мисконфигурейт исправлен

**Comment by thehaffk** [comment]
Подумали над тем чтобы в фоллбеках была иерархия(user lang -> default -> fallback(included with plugin)), но сейчас всем лень это делать, P10 таск
