### ISSUE TITLE
На креатив стоит добавить /flyspeed и /speed

### ISSUE THREAD

**Issue by Faustyu1** [digitaldrugstech/prdxsotech-bugtracker#31]
### Четкое и сжатое описание проблемы

flyspeed and speed

### Опишите решение, которое вы хотели бы получить

добавить в пермишены к игроку возможность на команду флайспид и спид

### Опишите альтернативы, которые вы рассматривали

*No response*

### Дополнительный контекст

*No response*

**Comment by thehaffk** [comment]
мне лень, НЕ БУДЕТ
пользуйтесь аксиомом

**Comment by Faustyu1** [comment]
спасибо🐝
