### ISSUE TITLE
Баны и муты не учитывают иерархию ролей

### ISSUE THREAD

**Issue by vrtkk** [digitaldrugstech/prdxsotech-bugtracker#35]
любой человек с пермишеном может выдать наказание человеку выше себя, например интерполовец может замутить главу, а глава может забанить админа

**Comment by rsmanito** [comment]
Заняться мне нечем в лп звонить

**Comment by thehaffk** [comment]
не уверен касается ли это штрафов, но наверное надо не давать выдать третий красный (?)
или вовсе запретить

**Comment by rsmanito** [comment]
Бан варнами должен остаться у каких-то не админских ролей. Мне лично такая возможность была много раз полезной

Я предлагаю внести в ролес новый блок работы с пермишенами. Всунуть туда мапу роль-вес и ручку на два айдишника. В панишментах потом дергать эту ручку на серьезные действия: бан и разбан как командами, так и варнами. Действия командами просто проверять, а варнами – проверять право на выдачу/снятие последнего

**Comment by thehaffk** [comment]
Принято, но идея с хэшпамой подходит только в случае если она просто кэширует данные (вес каждой роли) из LP

Под действия, на которые влияют weights относятся
- [ ] Бан
- [ ] Выдача мута
- [ ] Снятие мута [Можно обсудить необходимость]
- [ ] Выдача желтого или красного варна, который приведет к бану [Этот кейс может сломать ситуацию когда интерпол банит АФКшного главу за просрочку штрафа, но такие случаи должны решаться руками. Потребуется во фронте и апишке штрафов такой случай не забыть]

Разбаны под кейс не подходят, у разбаненных нет ролей

**Comment by rsmanito** [comment]
В случае мутов нормальным решением было бы разрешать снятие в случае, если issuer снятия имеет роль выше или такую же, как и issuer выдачи

**Comment by rsmanito** [comment]
Принято в разработку

# eta: 8 yr

**Comment by Komo4ekoI** [comment]
Проблемой являются случаи когда глава ведет себя не адекватно и спамит в глобал чат. В таком случаи мут обязан быть выдан.

**Comment by thehaffk** [comment]
> Проблемой являются случаи когда глава ведет себя не адекватно и спамит в глобал чат. В таком случаи мут обязан быть выдан.

Это обсуждалось на Plasmo с кпидсом, ответ (с которым я полностью согласен) был примерно такой: Глава должен понимать какая ответственность ему идет, когда он поступает на такую должность. Вести себя так чтобы тебя хотели замутить, но не могли потому что ты глава - абуз полномочий и наказывается по правилам как за превышение полномочий, то-есть сначала предупреждение, а потом красный варн и снятие

**Comment by rsmanito** [comment]
Я полностью согласен с позицией выше. Поведение вышестоящих игроков всегда должно оцениваться строже, потому что они являются лицом организаций, а следственно и лицом проекта

**Comment by Komo4ekoI** [comment]
Я тоже согласен. Проблемой ПРП было то что на это закрывали глаза и главам просто выдавали мут. Поднял этот вопрос просто что бы сразу знать что делать в подобной ситуации.

**Comment by rsmanito** [comment]
Должно работать. Протестировано на мутах, но логика везде одна
