### ISSUE TITLE
На сервере можно отправить сообщение человеку не в сети

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdxsotech-bugtracker#47]
![image](https://github.com/user-attachments/assets/e54688d0-a820-480b-aed4-69d67ba9ffac)

Либо запретить отправлять сообщение, либо (пока нет мессенджера) отправлять на других платформах (ДС/ТГ/Пуши)

**Comment by Apehum** [comment]
Fixed by https://github.com/digitaldrugstech/MurChat/commit/3e7a997dd025bdfe1a92cfe4f9ce0a2d407ec162
