### ISSUE TITLE
Тикеты в дискорде не работают

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdxsotech-bugtracker#48]

**Comment by pristordev** [comment]
аааа зачем???????

**Comment by yapalitra** [comment]
аааааааааа сосал

**Comment by thehaffk** [comment]
Потыкали бота, не хотел подниматься в к0с, подняли, осталось роутинг для tickets.prdxso.tech настроить и самого бота везде поставить

**Comment by Komo4ekoI** [comment]
Доступ к https://tickets.prdxso.tech успешно восстановлен, мы внутри!!!

**Comment by thehaffk** [comment]
![image](https://github.com/user-attachments/assets/912404a7-7403-4aba-be37-f03457633e8e)

**Comment by megazvezda** [comment]
при открытии тикета выходит сообщение об ошибке, даже если тикет успешно открылся

![{936773A2-EC3C-426A-9A60-600CAD6FE94A}](https://github.com/user-attachments/assets/2139272a-128f-4796-8e62-35ede68ff8a6)

**Comment by Komo4ekoI** [comment]
Гандоны намержили блять версий, хуесосы, как я вас ненавижу

**Comment by Komo4ekoI** [comment]
работают кароч

**Comment by yapalitra** [comment]
Американцы пидорасы

**Comment by setupmember** [comment]
не ворк бля опять

**Comment by vrtkk** [comment]
теперь точно работает
