### ISSUE TITLE
Чат ложно распознает ссылки в сообщениях

### ISSUE THREAD

**Issue by megazvezda** [digitaldrugstech/prdxsotech-bugtracker#53]
### Опишите баг

числовые данные неправильно распознаются как ссылки

### Шаги для воспроизведения поведения

whysumi
 — Today at 22:14
где можно чаткор найти на [1.21](https://1.21) адекватный найти?

1.21 распознается как айпи по которому можно пройти в браузере

### Ожидаемое поведение

обычное отображение текста без возможности нажатия

**Comment by thehaffk** [comment]
Распознавание ссылок в принципе не очень круто работает 
![image](https://github.com/user-attachments/assets/3e995eb0-c329-46ef-b153-5eef2123d69a)

**Comment by Apehum** [comment]
partially fixed by https://github.com/digitaldrugstech/MurChat/commit/d58b9081db14d4ee0a9444c14a8c3390dfd4233b

Полностью адекватно это не пофиксить, но теперь хотя бы цифры не распознаются как домены первого уровня
