### ISSUE TITLE
Ускоренный скип ночи когда спишь (как в Террарии)

### ISSUE THREAD

**Issue by pepep00p00** [digitaldrugstech/prdxsotech-bugtracker#55]
### Четкое и сжатое описание проблемы

Не все готовы ложится спать чтобы скипнуть ночь

### Опишите решение, которое вы хотели бы получить

Я хочу, чтобы скип ночи работал так: ускорялся в 4 раза (может меньше, может больше) при 20 онлайна, в 2 раза при 40 онлайна т.д. Цифры могут менятся, но суть понятна.

И надо чтобы все видели снизу над уровнем здоровья что ночь ускоряется

### Опишите альтернативы, которые вы рассматривали

Думаю просто уменьшение количества людей для скипа ночи недостаточно, чтобы решить эту проблему. При моём предложении все будут довольны.

**Comment by pepep00p00** [comment]
> Мне кажется, что люди, которым нужно пропустить ночь, чаще нуждаются в моментальном эффекте, а не в ускорении. За то время, что игрок будет лежать в кровати и ждать рассвета, он мог бы сделать что-то другое, не зависящее от времени дня
> 
> Подобный функционал заставляет людей полностью прерываться от игры. Несмотря на то, что так игроки научатся делать перерывы, понравится это, подозреваю, далеко не всем
> 
> Подправь, если я где-то ошибся

**Comment by thehaffk** [comment]
может я чего-то не понимаю, но зачем ты скопировал его сообщение

**Comment by pixiemays** [comment]
Сейчас мы не сильно хотим добавлять это на сервер, потому что это слишком не ванильно, да и огромного желания добавлять это у нас нет.

Все подобные идеи можно обсудить и принять на совете МКО на основном сервере, когда тот откроется.
