### ISSUE TITLE
Уведомления о мутах, банах и варнах не приходят в чат в майнкрафте

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdxsotech-bugtracker#58]
А должны! Пока не поддерживается, ни мурчатом, ни сервисом уведомлений

**Comment by thehaffk** [comment]
Ебаный комочек ради этого переписывает весь @digitaldrugstech/notification-service на Go

https://github.com/digitaldrugstech/notifications-service/pull/28

Лапы отрезать мало.

**Comment by thehaffk** [comment]
приходят, но не форматируются

**Comment by Apehum** [comment]
приходят и форматируются
![image](https://github.com/user-attachments/assets/21072cac-72c4-4601-84d8-1e4af2486157)
