### ISSUE TITLE
Счетчик онлайна в канал #игра

### ISSUE THREAD

**Issue by megazvezda** [digitaldrugstech/prdxsotech-bugtracker#64]
### Четкое и сжатое описание проблемы

Счетчик онлайна в канал #игра

### Опишите решение, которое вы хотели бы получить

отображение счетчика игроков в описании канала

**Comment by thehaffk** [comment]
![image](https://github.com/user-attachments/assets/71c9120f-200a-4277-a09a-a355678b2322)
