### ISSUE TITLE
Невозможно открыть карту на сайте 

### ISSUE THREAD

**Issue by TheSkittish** [digitaldrugstech/prdxsotech-bugtracker#70]
### Опишите баг

Бесконечное открытие начальной страницы

### Шаги для воспроизведения поведения

1.Зайдите на https://prdxso.tech/ 2. Нажмите на "Карта"

### Ожидаемое поведение

Ожидал страницу с примерной надписью "Карта временно недоступна"

### Если возможно, прикрепите скриншоты или видео

![Снимок экрана 2024-11-18 183410](https://github.com/user-attachments/assets/06f1860a-7fe3-48ed-b897-1b689e4aa37b)

**Comment by thehaffk** [comment]
Ну ошибка там теперь 404, но к карте доступ получить все еще нельзя

**Comment by s3nkwr** [comment]
Ну теперь там есть ЛайвАтлас. Осталось его настроить и все :)

**Comment by Komo4ekoI** [comment]
> Ну теперь там есть ЛайвАтлас. Видимо Апехум посмотрел и пофиксил уже полностью. Осталось его настроить и все :)

Наверное не апехум

**Comment by s3nkwr** [comment]
> Наверное не апехум
Я сделала фикс только на путь по которому сервер html подтягивает. Оно работало на Компоузе, но не работало на той конфигурации в Кубернетисах. Апехум вроде и починил её.

**Comment by thehaffk** [comment]
> > Ну теперь там есть ЛайвАтлас. Видимо Апехум посмотрел и пофиксил уже полностью. Осталось его настроить и все :)
> 
> Наверное не апехум

наверное без тупых комментариев в issue

**Comment by thehaffk** [comment]
https://prdxso.tech/map
