### ISSUE TITLE
Пепега не должна отвечать на "когда" в категориях тикетов

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdxsotech-bugtracker#72]
![image](https://github.com/user-attachments/assets/6fd24d79-04e7-4037-8a2d-281e67f263ba)

Мешает тикету, но по большей части это еще и ломает AI_Support

**Comment by Komo4ekoI** [comment]
@Chexit в is env нужно добавить 'ROFLS_BLACKLIST_CATEGORIES' и такой же для каналов, потом импортируешь их в конфиг app через set(). После чего добавь проверки перед отправкой рофлов

**Comment by Komo4ekoI** [comment]
готово, @Chexit уволен
