### ISSUE TITLE
Бот на тикеты иногда присылает ошибку без ошибки

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdxsotech-bugtracker#75]
![image](https://github.com/user-attachments/assets/1195505b-aa91-4a42-84ce-0adfa9850991)

**Comment by Komo4ekoI** [comment]
Через год будет йоу

**Comment by Komo4ekoI** [comment]
![image](https://github.com/user-attachments/assets/7eb2b392-0f63-4409-b129-08b2de69f8f0)
fixed
