### ISSUE TITLE
Ачивки выдаются только после перезахода на сервер

### ISSUE THREAD

**Issue by otomir23** [digitaldrugstech/prdxsotech-bugtracker#76]
### Опишите баг

Когда выполняешь ачивку не появляется тост и она не отображается выполненной в дереве до перезахода

### Шаги для воспроизведения поведения

1. Зайти в ад
2. Убить гаста файрболом
3. НЕ ПОЛУЧИТЬ красивый тост и звук  и почести((

### Ожидаемое поведение

я поулчаю тост и звук и вообще круто

**Comment by Apehum** [comment]
Fixed by https://github.com/digitaldrugstech/SkipAdvancementSend/commit/34171f978ea590f48493b021cfd1787fe3075f91
