### ISSUE TITLE
Аватарки и скины должно быть можно получить с .png

### ISSUE THREAD

**Issue by thehaffk** [digitaldrugstech/prdxsotech-bugtracker#79]
На бекенде можно просто игнорировать .png в конце

prdxso.tech/avatar/vrtkk.png = prdxso.tech/avatar/vrtkk

оно вроде и так файлом приходит, так что эээ, не сильно менять нужно

**Comment by Murchik0v** [comment]
добавьте этому апи еще и возможность получить скин игрока под разными ракурсами

**Comment by thehaffk** [comment]
> добавьте этому апи еще и возможность получить скин игрока под разными ракурсами

сам отрендеришь

**Comment by thehaffk** [comment]
не робе 
![image](https://github.com/user-attachments/assets/34030a52-9e61-4655-9249-dc402955d3ed)

**Comment by sryosz** [comment]
не робе, бо бренча в дев не замержена

**Comment by thehaffk** [comment]
замержи

**Comment by sryosz** [comment]
САМ ЗАМЕРЖЬІ ИДИОТИНА, Я РИЛСЬІ СМОТРЮ

**Comment by sryosz** [comment]
ИДИОТ, ОНО ЕЩЕ УТРОМ ЗАМЕРЖЕНО

**Comment by thehaffk** [comment]
![image](https://github.com/user-attachments/assets/b23ef17a-70eb-4051-870b-99f5b51fcd4a)

**Comment by sryosz** [comment]
перезапусти его, идиот

**Comment by thehaffk** [comment]
![image](https://github.com/user-attachments/assets/766e889c-f6e8-49d1-937d-d2fcb5552e0b)
