### ISSUE TITLE
Не кикает после бана

### ISSUE THREAD

**Issue by matBast0s** [digitaldrugstech/prdxsotech-bugtracker#80]
### Опишите баг

После бана человека его не кикнуло

### Шаги для воспроизведения поведения

1. Зайдите на парадох
2. Сделайте чтото плохое
3. Получите БАН
4. Не вылетите и играте до выключения вашего интернета

### Ожидаемое поведение

Человек должен вылететь после бана

**Comment by thehaffk** [comment]
https://github.com/digitaldrugstech/PunishmentsPlugin/issues/3

**Comment by megazvezda** [comment]
теперь после бана игрока кикает, а причина корректно отображается на экране забаненного

**Comment by megazvezda** [comment]
спасибо апехуму
