### ISSUE TITLE
Добавить крафт блока света

### ISSUE THREAD

**Issue by SoLuvUQ** [digitaldrugstech/prdxsotech-bugtracker#87]
### Четкое и сжатое описание проблемы

Многие строители используют этот блок в своих постройках, из-за чего из отсутствие может сказаться на качестве работ игроков

### Опишите решение, которое вы хотели бы получить

предлагаю такой вариант крафта для блока света, поскольку он достаточно дорогой для добычи (крафт в размере 3х штук)
![crafting-grid](https://github.com/user-attachments/assets/2b0a746e-7588-4161-bd30-39f171d7a1c1)

**Comment by pixiemays** [comment]
![image](https://github.com/user-attachments/assets/8d38dfa4-7112-4d81-beae-205a3db30b5f)

**Comment by thehaffk** [comment]
В идеале переделать на предложенный рецепт 
![image](https://github.com/user-attachments/assets/9d0f86d7-6e55-463b-9621-e1c33f2b74d1)
@pixiemays

**Comment by pixiemays** [comment]
![image](https://github.com/user-attachments/assets/1c0cd773-7d8c-408f-9fee-3981ff28a0f7)
