### ISSUE TITLE
Блок портала в МФ пропадает при взаимодействии с поршнем

### ISSUE THREAD

**Issue by megazvezda** [digitaldrugstech/prdxsotech-bugtracker#89]
### Опишите баг

я сам не понимаю что это

### Шаги для воспроизведения поведения

установите конструкцию с поршнем, блоком и блоком редстоуна как на скриншотах
блок портала сломается для всех игроков

если сломать все 6 блоков портала, портал останется активным и в него можно будет зайти, просто без видимости портала

### Ожидаемое поведение

????

### Если возможно, прикрепите скриншоты или видео

https://www.youtube.com/watch?v=mcYyHz3cTMA

### Любая дополнительная информация

я не понимаю что это и оформлено поэтому все тоже не очень

**Comment by megazvezda** [comment]
может быть связано с https://github.com/digitaldrugstech/prdxsotech-bugtracker/issues/88 и я просто зря открыл этот

**Comment by megazvezda** [comment]
другой игрок подтвердил что блок ломается !

**Comment by Apehum** [comment]
Fixed by https://github.com/digitaldrugstech/LinkedPortals/commit/257265bed8b49cacd6cdd4887a2b3d281711d403
