### ISSUE TITLE
Слетает авторизация на сайте каждые сутки

### ISSUE THREAD

**Issue by savas12-sys** [digitaldrugstech/prdxsotech-bugtracker#90]
### Опишите баг

Слетает авторизация на сайте каждые сутки и нужно заного логинится

### Шаги для воспроизведения поведения

1.Авторизоваться на сайте
2.Подождать сутки
3.Через сутки Авторизация слетит

### Ожидаемое поведение

Авторизация не должна слетать.

### Если возможно, прикрепите скриншоты или видео

нету

**Comment by thehaffk** [comment]
Куки с токеном ставятся в Max-Age: Session
Поэтому в браузерах, в которых выключена "Continue where i left off" настройка слетает авторизация при переоткрытии всех окон
![image](https://github.com/user-attachments/assets/0d0a7487-18b8-4c08-91f1-7f3b37c1dc28)
![image](https://github.com/user-attachments/assets/83518bf5-e952-4fbc-a25a-260fb856e47d)
![image](https://github.com/user-attachments/assets/8328b65f-1c1c-4828-8cc6-2a625f4ac877)
![image](https://github.com/user-attachments/assets/fdd24c92-e502-4bdc-b0f7-fc81c1f00cfa)

**Comment by Apehum** [comment]
![image](https://github.com/user-attachments/assets/6181df84-5791-40f2-a0c1-78440cb5fd9c)
