### ISSUE TITLE
Дюп ТНТ не работает

### ISSUE THREAD

**Issue by matBast0s** [digitaldrugstech/prdxsotech-bugtracker#94]
### Опишите баг

не работает дюп тнт с помощью механизма

### Шаги для воспроизведения поведения

1. Заходишь на сервер
2. Строишь любую дюп машинку тнт
3. Она не работает

### Ожидаемое поведение

Начнётся размножение тнт почкованием

**Comment by thehaffk** [comment]
теоретически могло пофикситься (https://github.com/digitaldrugstech/rp-plugins/pull/17)

@matBast0s проверь и отпишись/закрой issue
